### ISSUE TITLE
Documentation improvement - Include Annotation For Commands

### ISSUE THREAD

**Issue by joszo** [90poe/vscode-cy-helper#11]
Hello,

Currently, I’m testing your extensions and it would be nice if you add an example of usage for `Include Annotation For Commands`. 

So far I found that usage
```
// Find input, and fill it with the values
// @example
// cy.fillInput('.input', 'someValue')
Cypress.Commands.add('fillInput', (element, text) => {
	cy.get(element).type(text);
});
```

Will generate result:

```
declare namespace Cypress {
    interface Chainable<Subject> {
        /* cy.fillInput('.input', 'someValue')*/
        fillInput(element: any, text: any): Chainable<any>
  }
}
```

I've made so digging into code and I think the reason is in the `leadingComment`. It takes only the first comment so if we have a couple of comments with `//` it will take only the last one.

```
/* Find input, and fill it with the values
@example
cy.fillInput('.input', 'someValue') */
Cypress.Commands.add('fillInput', (element, text) => {
	cy.get(element).type(text);
});
```

Above `/* ... */` will fix the problem but we still don't see the `documentation` of the method in the spec file.

![Screen Shot 2019-12-10 at 11 52 52 AM](https://user-images.githubusercontent.com/32454314/70523711-e9f30c80-1b43-11ea-990c-be840c76308e.png)

So the best way of usage would be

```
/** Find input, and fill it with the values
* @example
* cy.fillInput('.input', 'someValue')
*/
Cypress.Commands.add('fillInput', (element, text) => {
	cy.get(element).type(text);
});
```

And the result in spec file:

![Screen Shot 2019-12-10 at 11 45 12 AM](https://user-images.githubusercontent.com/32454314/70523868-32122f00-1b44-11ea-8157-54f19b7ef3f0.png)

I know a lot of people are lazy so that small documentation updated would save time for some of them.  :)

**Comment by Shelex** [comment]
@joszo Have upgraded documentation `Cypress: Generate custom command types` section with information that annotations should be in JSDoc format.

**Comment by joszo** [comment]
Thanks a lot! For new users, it will be more understandable.
