### ISSUE TITLE
Custom command folder setting not working?

### ISSUE THREAD

**Issue by jdvegmond** [90poe/vscode-cy-helper#16]
I've set the following in my .vscode/settings.json:
"cypressHelper.customCommandsFolder": "tests/e2e/support"
In that folder the commands.js is present, with a custom command.

But when I use F12 from my code to go to that custom command, I get an error in the bottom of my screen:
Unable to open 'commands.js': resource is not available.
The file with the code where I'm coming from is closed (if nothing was altered).

![2020-02-28 12_58_16-Window](https://user-images.githubusercontent.com/32638636/75546933-08bdbc80-5a2a-11ea-9ee6-4eefaa0b6aad.png)
![2020-02-28 12_58_52-Window](https://user-images.githubusercontent.com/32638636/75546959-196e3280-5a2a-11ea-9e6d-74abd666bd90.png)
![2020-02-28 12_59_15-Window](https://user-images.githubusercontent.com/32638636/75546982-29861200-5a2a-11ea-820e-7c2d249ff4cf.png)

**Comment by Shelex** [comment]
@jdvegmond Thank you for posting an issue!
Have investigated it a bit and found that it may be connected with method i am using for parsing vscode URI for files.
Published version 0.4.2, could you please check if it works for your case?

**Comment by jdvegmond** [comment]
> @jdvegmond Thank you for posting an issue!
> Have investigated it a bit and found that it may be connected with method i am using for parsing vscode URI for files.
> Published version 0.4.2, could you please check if it works for your case?

I've checked it. It works fine now! Thanks!
