### ISSUE TITLE
Allow multiple paths for Custom Commands Folder

### ISSUE THREAD

**Issue by shwarcu** [90poe/vscode-cy-helper#18]
**Is your feature request related to a problem? Please describe.**
In our solution, we keep most of Cypress commands in cypress/support folder. However some commands are specific to certain application areas and are defined somewhere else.

_Go to custom command definition_ option does not work for such cases.

**Describe the solution you'd like**
It would be a highly valuable feature to be able to set more than 1 path for Custom Commands Folder setting.

**Comment by Shelex** [comment]
Thank you for posting a feature request.

Could you please clarify what you mean by `defined somewhere else` - is it still inside cypress folder or in other workspace subfolders? Just in case they are all defined inside `cypress` you can just set it as source for custom commands. Or do you want some kind of ['app/cypress/support', 'app/src/component/cypressCommands']?

**Comment by Shelex** [comment]
Closing as there is no more input about value of such feature provided.
