### ISSUE TITLE
I don't get the 'Cypress: Open single test' option nor 'Cypress: Open spec file'

### ISSUE THREAD

**Issue by LeonardoGobbiLopez** [90poe/vscode-cy-helper#21]
**Describe the bug**
I added the extension and don't have these two options

**To Reproduce**
Steps to reproduce the behaviour:
1. Add extension
2. Go to file with it statement
3. These two options doesn't show

**Expected behaviour**
The options should show

**Environment (please complete the following information):**
- Extension version:                               0.5.2
- VS Code version:                                1.45
- OS:                                                     Mac:

![image](https://user-images.githubusercontent.com/40830059/81404413-c8ef1180-910b-11ea-86c1-89e0c6b984bb.png)

**Comment by Shelex** [comment]
Hello @LeonardoGobbiLopez!
Thank you for posting an issue.

Could you please clarify:
- do you have test files using typescript? 
- have you edited configuration "cypressHelper.menuItems"?

**Comment by Shelex** [comment]
@LeonardoGobbiLopez Just published extension version 0.6.0 with ts support added. Could you please check if it solves your case?

**Comment by LeonardoGobbiLopez** [comment]
Yes! It worked like a charm.
Just had to change the 'cypress open' to my 'yarn cy' call in the package.json

Good job man, you the best :D
