### ISSUE TITLE
Optional args not following to definition

### ISSUE THREAD

**Issue by dusty** [90poe/vscode-cy-helper#27]
With the following custom command

```
Cypress.Commands.add('test123', (param1: string, param2?: string) => {
  console.log(param1, param2)
})
```

The following type definition is being generated
```
 test123(param1: string, param2: string): Chainable<any>
```

The param2 is listed as required in the definition.

**Comment by Shelex** [comment]
Hello @dusty 
thank you for opening an issue!

Just published v0.8.2 where it should be resolved. 
Could you please check it on your side?
