### ISSUE TITLE
Would you mind publishing this extension to Open VSX Registry?

### ISSUE THREAD

**Issue by entrywayaudibly** [90poe/vscode-cy-helper#28]
Doing so would support code editors like VSCodium, because this editor's `product.json` file is set up to use open-vsx.org as extension gallery.

Hence, if extension maintainers don't publish to [Open VSX Registry][open-vsx], users may face some problems:

- Unable to find and download the extension, directly from the editor;
- Unable to have [Settings Sync][settings-sync] download and install the extension;
- Being forced to manually download and install the extension.

The publishing process is documented in the [Open VSX Wiki][open-vsx-publish].

[open-vsx]: https://open-vsx.org/
[open-vsx-publish]: https://github.com/eclipse/openvsx/wiki/Publishing-Extensions
[settings-sync]: https://code.visualstudio.com/docs/editor/settings-sync

**Comment by Shelex** [comment]
@entrywayaudibly Deployment steps for Open VSX have been added.
You can find Cypress Helper published - https://open-vsx.org/extension/Shelex/vscode-cy-helper
