### ISSUE TITLE
Relaunch on next test

### ISSUE THREAD

**Issue by ambrt** [90poe/vscode-cy-helper#29]
Everything works good except the fact that if i do "Open cypress" once, and than do it for another test (without closing the gui app) it will not relaunch cypress with new spec file.

It just  prints command for new test to VS code terminal.

Having opening and closing it every time should be somehow cutted off.

**Comment by Shelex** [comment]
Thanks for opening a feature request!
By the way, we find it very convenient to not respawn cypress instance as it helps to debug several tests separately located in one file. But I may consider adding a feature toggle to respawn terminal every time. 
However, for now I suggest to just close the terminal and all focus/.only tags will be removed and cypress instance being shut down, and then new one could be opened

**Comment by Shelex** [comment]
@ambrt Have published 0.9.0 with configuration option `cypressHelper.reuseTerminalInstance`.
Set it to `false` and terminal will be respawned each time you use "Open Cypress"

**Comment by ambrt** [comment]
> @ambrt Have published 0.9.0 with configuration option `cypressHelper.reuseTerminalInstance`.
> Set it to `false` and terminal will be respawned each time you use "Open Cypress"

Ok i see it working now. 
The "why" behind is that i write specs in granular way - most of tests have their own file.
When i want to test whole suite of specs i require them in "meta" spec file to not respawn window for each file.
Thanks for update!
